# Generated by Django 2.1.7 on 2019-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_bachelor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelor_data',
            name='number',
            field=models.IntegerField(),
        ),
    ]
