# Generated by Django 2.1.7 on 2019-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190531_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoT_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
            ],
        ),
    ]
