# Generated by Django 2.1.7 on 2019-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_iot_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoT_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
            ],
        ),
    ]
